import "dotenv/config";
import { drizzle } from "drizzle-orm/neon-http";
import { neon } from "@neondatabase/serverless";

import * as schema from "../db/schema";

const sql = neon(process.env.DATABASE_URL!);
// @ts-ignore
const db = drizzle(sql, { schema });

const main = async () => {
  try {
    // Clean existing data
    await db.delete(schema.userProgress);
    await db.delete(schema.challengeProgress);
    await db.delete(schema.challengeOptions);
    await db.delete(schema.challenges);
    await db.delete(schema.lessons);
    await db.delete(schema.units);
    await db.delete(schema.courses);
    await db.delete(schema.userSubscription);

    await db.insert(schema.courses).values([
      { id: 1, title: "Mathematics", imageSrc: "/math.svg" },
      { id: 2, title: "Spanish", imageSrc: "/es.svg" },
      { id: 3, title: "Italian", imageSrc: "/it.svg" },
      { id: 4, title: "French", imageSrc: "/fr.svg" },
      { id: 5, title: "Croatian", imageSrc: "/hr.svg" },
      { id: 6, title: "Culture Générale", imageSrc: "/culture.svg" },
    ]);

    // ================================================
    // 1. MATHÉMATIQUES (Course ID: 1)
    // ================================================

    await db.insert(schema.units).values([
      { id: 1, courseId: 1, title: "Équations", description: "Équations du 1er et 2ème degré", order: 1 },
      { id: 2, courseId: 1, title: "Fractions & Proportions", description: "Maîtrise les fractions et les proportions", order: 2 },
      { id: 3, courseId: 1, title: "Géométrie", description: "Aires, périmètres et théorèmes", order: 3 },
      { id: 4, courseId: 1, title: "Statistiques", description: "Moyenne, médiane et probabilités", order: 4 },
      { id: 11, courseId: 1, title: "Dérivées & Intégrales", description: "Calcul différentiel et intégral", order: 5 },
      { id: 12, courseId: 1, title: "Trigonométrie Avancée", description: "Identités et équations trigonométriques", order: 6 },
      { id: 13, courseId: 1, title: "Nombres Complexes", description: "Algèbre et géométrie des complexes", order: 7 },
      { id: 14, courseId: 1, title: "Algèbre Linéaire", description: "Matrices et systèmes linéaires avancés", order: 8 },
    ]);

    await db.insert(schema.lessons).values([
      { id: 1, unitId: 1, order: 1, title: "Équations du 1er degré" },
      { id: 2, unitId: 1, order: 2, title: "Équations du 2ème degré" },
      { id: 3, unitId: 1, order: 3, title: "Systèmes d'équations" },
      { id: 4, unitId: 2, order: 1, title: "Simplification de fractions" },
      { id: 5, unitId: 2, order: 2, title: "Opérations sur les fractions" },
      { id: 6, unitId: 2, order: 3, title: "Proportions & règle de trois" },
      { id: 7, unitId: 3, order: 1, title: "Aires et périmètres" },
      { id: 8, unitId: 3, order: 2, title: "Théorème de Pythagore" },
      { id: 9, unitId: 3, order: 3, title: "Théorème de Thalès" },
      { id: 10, unitId: 4, order: 1, title: "Moyenne et médiane" },
      { id: 11, unitId: 4, order: 2, title: "Probabilités de base" },
      { id: 25, unitId: 11, order: 1, title: "Dérivées de fonctions simples" },
      { id: 26, unitId: 11, order: 2, title: "Règle de la chaîne" },
      { id: 27, unitId: 11, order: 3, title: "Intégrales définies" },
      { id: 28, unitId: 11, order: 4, title: "Primitives et intégrales indéfinies" },
      { id: 29, unitId: 12, order: 1, title: "Identités trigonométriques" },
      { id: 30, unitId: 12, order: 2, title: "Équations trigonométriques" },
      { id: 31, unitId: 12, order: 3, title: "Formules d'addition" },
      { id: 32, unitId: 13, order: 1, title: "Forme algébrique" },
      { id: 33, unitId: 13, order: 2, title: "Module et argument" },
      { id: 34, unitId: 13, order: 3, title: "Forme trigonométrique" },
      { id: 35, unitId: 14, order: 1, title: "Opérations sur les matrices" },
      { id: 36, unitId: 14, order: 2, title: "Déterminant et inverse" },
      { id: 37, unitId: 14, order: 3, title: "Systèmes linéaires (méthode de Gauss)" },
    ]);

    await db.insert(schema.challenges).values([
      { id: 1, lessonId: 1, type: "ASSIST", order: 1, question: "Résous : 3x + 7 = 2x + 15" },
      { id: 2, lessonId: 1, type: "ASSIST", order: 2, question: "Résous : 5(x - 2) = 3(x + 4)" },
      { id: 3, lessonId: 1, type: "ASSIST", order: 3, question: "Résous : 7x - 9 = 5x + 15" },
      { id: 4, lessonId: 1, type: "ASSIST", order: 4, question: "Résous : 4(2x - 1) = 6x + 10" },
      // 👇 FILL_BLANK maths — leçon 1
      { id: 200, lessonId: 1, type: "FILL_BLANK", order: 5, question: "Si 3x + 7 = 2x + 15, alors x = ___" },
      { id: 201, lessonId: 1, type: "FILL_BLANK", order: 6, question: "Si 5x - 3 = 2x + 9, alors x = ___" },
      { id: 202, lessonId: 1, type: "FILL_BLANK", order: 7, question: "Si 4(x + 2) = 24, alors x = ___" },

      { id: 5, lessonId: 2, type: "ASSIST", order: 1, question: "Résous : x² - 9 = 0" },
      { id: 6, lessonId: 2, type: "ASSIST", order: 2, question: "Résous : 2x² - 18 = 0" },
      { id: 7, lessonId: 2, type: "ASSIST", order: 3, question: "Résous : (x - 4)(2x + 6) = 0" },
      { id: 8, lessonId: 2, type: "ASSIST", order: 4, question: "Résous : (x + 2)² = 49" },
      { id: 9, lessonId: 2, type: "ASSIST", order: 5, question: "Résous : x² - 5x + 6 = 0" },
      // 👇 FILL_BLANK maths — leçon 2
      { id: 203, lessonId: 2, type: "FILL_BLANK", order: 6, question: "Si x² = 25, alors x = ___ ou x = ___" },
      { id: 204, lessonId: 2, type: "FILL_BLANK", order: 7, question: "Si x² - 7x + 12 = 0, alors x = ___ ou x = ___" },

      { id: 10, lessonId: 3, type: "ASSIST", order: 1, question: "Résous : x + y = 10 et x - y = 4" },
      { id: 11, lessonId: 3, type: "ASSIST", order: 2, question: "Résous : 2x + y = 7 et x - y = 2" },
      { id: 12, lessonId: 3, type: "ASSIST", order: 3, question: "Résous : 3x + 2y = 12 et x + y = 5" },
      { id: 13, lessonId: 3, type: "ASSIST", order: 4, question: "Résous : x + 2y = 8 et 2x - y = 1" },

      { id: 14, lessonId: 4, type: "SELECT", order: 1, question: "Simplifie : 12/18" },
      { id: 15, lessonId: 4, type: "SELECT", order: 2, question: "Simplifie : 24/36" },
      { id: 16, lessonId: 4, type: "SELECT", order: 3, question: "Simplifie : 15/45" },
      { id: 17, lessonId: 4, type: "SELECT", order: 4, question: "Simplifie : 28/42" },
      // 👇 FILL_BLANK maths — leçon 4
      { id: 205, lessonId: 4, type: "FILL_BLANK", order: 5, question: "12/18 simplifié donne ___" },
      { id: 206, lessonId: 4, type: "FILL_BLANK", order: 6, question: "15/45 simplifié donne ___ et 24/36 donne ___" },

      { id: 18, lessonId: 5, type: "SELECT", order: 1, question: "Calcule : 1/2 + 1/3" },
      { id: 19, lessonId: 5, type: "SELECT", order: 2, question: "Calcule : 3/4 - 1/6" },
      { id: 20, lessonId: 5, type: "SELECT", order: 3, question: "Calcule : 2/3 × 3/4" },
      { id: 21, lessonId: 5, type: "SELECT", order: 4, question: "Calcule : 5/6 ÷ 5/3" },
      // 👇 FILL_BLANK maths — leçon 5
      { id: 207, lessonId: 5, type: "FILL_BLANK", order: 5, question: "1/2 + 1/3 = ___" },
      { id: 208, lessonId: 5, type: "FILL_BLANK", order: 6, question: "2/3 × 3/4 = ___ et 5/6 ÷ 5/3 = ___" },

      { id: 22, lessonId: 6, type: "SELECT", order: 1, question: "Si 3 stylos coûtent 6€, combien coûtent 7 stylos ?" },
      { id: 23, lessonId: 6, type: "SELECT", order: 2, question: "Une voiture roule 150 km en 2h. Quelle distance en 5h ?" },
      { id: 24, lessonId: 6, type: "SELECT", order: 3, question: "4 ouvriers font un travail en 6 jours. Combien faut-il d'ouvriers pour 3 jours ?" },

      { id: 25, lessonId: 7, type: "SELECT", order: 1, question: "Quelle est l'aire d'un rectangle de 6cm × 4cm ?" },
      { id: 26, lessonId: 7, type: "SELECT", order: 2, question: "Quel est le périmètre d'un carré de côté 5cm ?" },
      { id: 27, lessonId: 7, type: "SELECT", order: 3, question: "Quelle est l'aire d'un triangle de base 8cm et hauteur 5cm ?" },
      { id: 28, lessonId: 7, type: "SELECT", order: 4, question: "Quelle est l'aire d'un cercle de rayon 7cm ? (π ≈ 3.14)" },
      // 👇 FILL_BLANK maths — leçon 7
      { id: 209, lessonId: 7, type: "FILL_BLANK", order: 5, question: "L'aire d'un rectangle de 6cm × 4cm est ___ cm²" },
      { id: 210, lessonId: 7, type: "FILL_BLANK", order: 6, question: "Le périmètre d'un carré de côté 5cm est ___ cm" },

      { id: 29, lessonId: 8, type: "SELECT", order: 1, question: "Triangle rectangle : a=3, b=4. Quelle est la valeur de c ?" },
      { id: 30, lessonId: 8, type: "SELECT", order: 2, question: "Triangle rectangle : a=5, b=12. Quelle est la valeur de c ?" },
      { id: 31, lessonId: 8, type: "SELECT", order: 3, question: "Triangle rectangle : c=10, a=6. Quelle est la valeur de b ?" },
      // 👇 FILL_BLANK maths — leçon 8
      { id: 211, lessonId: 8, type: "FILL_BLANK", order: 4, question: "Si a = 3 et b = 4, alors c = ___" },
      { id: 212, lessonId: 8, type: "FILL_BLANK", order: 5, question: "Si a = 5 et b = 12, alors c = ___" },

      { id: 32, lessonId: 9, type: "SELECT", order: 1, question: "Si AB=6, AC=9 et AD=4, quelle est la longueur AE ?" },
      { id: 33, lessonId: 9, type: "SELECT", order: 2, question: "Si AB=8, DE=4 et AD=3, quelle est la longueur BC ?" },

      { id: 34, lessonId: 10, type: "SELECT", order: 1, question: "Quelle est la moyenne de : 4, 8, 6, 10, 2 ?" },
      { id: 35, lessonId: 10, type: "SELECT", order: 2, question: "Quelle est la médiane de : 3, 7, 1, 9, 5 ?" },
      { id: 36, lessonId: 10, type: "SELECT", order: 3, question: "Quelle est la moyenne de : 12, 15, 18, 9, 6 ?" },
      // 👇 FILL_BLANK maths — leçon 10
      { id: 213, lessonId: 10, type: "FILL_BLANK", order: 4, question: "La moyenne de 4, 8, 6, 10, 2 est ___" },
      { id: 214, lessonId: 10, type: "FILL_BLANK", order: 5, question: "La médiane de 3, 7, 1, 9, 5 est ___" },

      { id: 37, lessonId: 11, type: "SELECT", order: 1, question: "On lance un dé. Quelle est la probabilité d'obtenir 6 ?" },
      { id: 38, lessonId: 11, type: "SELECT", order: 2, question: "On tire une carte dans un jeu de 52. Probabilité d'un as ?" },
      { id: 39, lessonId: 11, type: "SELECT", order: 3, question: "On lance une pièce 2 fois. Probabilité d'obtenir 2 faces ?" },

      { id: 60, lessonId: 25, type: "SELECT", order: 1, question: "Quelle est la dérivée de f(x) = x³ + 2x² - 5x + 3 ?" },
      { id: 61, lessonId: 25, type: "SELECT", order: 2, question: "Quelle est la dérivée de f(x) = sin(x) + cos(x) ?" },
      { id: 62, lessonId: 25, type: "SELECT", order: 3, question: "Quelle est la dérivée de f(x) = eˣ · x² ?" },
      { id: 63, lessonId: 25, type: "SELECT", order: 4, question: "Quelle est la dérivée de f(x) = ln(x) / x ?" },
      // 👇 FILL_BLANK maths — leçon 25
      { id: 215, lessonId: 25, type: "FILL_BLANK", order: 5, question: "La dérivée de x³ est ___ et la dérivée de x⁴ est ___" },
      { id: 216, lessonId: 25, type: "FILL_BLANK", order: 6, question: "La dérivée de sin(x) est ___ et la dérivée de cos(x) est ___" },

      { id: 64, lessonId: 26, type: "SELECT", order: 1, question: "Dérive f(x) = (3x² + 1)⁴" },
      { id: 65, lessonId: 26, type: "SELECT", order: 2, question: "Dérive f(x) = sin(2x + 1)" },
      { id: 66, lessonId: 26, type: "SELECT", order: 3, question: "Dérive f(x) = e^(x² - 1)" },
      { id: 67, lessonId: 26, type: "SELECT", order: 4, question: "Dérive f(x) = ln(cos(x))" },

      { id: 68, lessonId: 27, type: "SELECT", order: 1, question: "Calcule ∫₀² x² dx" },
      { id: 69, lessonId: 27, type: "SELECT", order: 2, question: "Calcule ∫₁³ (2x + 1) dx" },
      { id: 70, lessonId: 27, type: "SELECT", order: 3, question: "Calcule ∫₀^π sin(x) dx" },
      { id: 71, lessonId: 27, type: "SELECT", order: 4, question: "Calcule ∫₁^e (1/x) dx" },

      { id: 72, lessonId: 28, type: "SELECT", order: 1, question: "Quelle est une primitive de f(x) = 3x² + 2x ?" },
      { id: 73, lessonId: 28, type: "SELECT", order: 2, question: "Quelle est une primitive de f(x) = cos(x) ?" },
      { id: 74, lessonId: 28, type: "SELECT", order: 3, question: "Quelle est une primitive de f(x) = 1/(x+1) ?" },

      { id: 75, lessonId: 29, type: "SELECT", order: 1, question: "Simplifie : sin²(x) + cos²(x)" },
      { id: 76, lessonId: 29, type: "SELECT", order: 2, question: "Quelle est la valeur de cos(2x) en termes de sin(x) ?" },
      { id: 77, lessonId: 29, type: "SELECT", order: 3, question: "Simplifie : (1 - cos²(x)) / sin(x)" },
      { id: 78, lessonId: 29, type: "SELECT", order: 4, question: "Quelle est la valeur de tan²(x) + 1 ?" },
      // 👇 FILL_BLANK maths — leçon 29
      { id: 217, lessonId: 29, type: "FILL_BLANK", order: 5, question: "sin²(x) + cos²(x) = ___" },
      { id: 218, lessonId: 29, type: "FILL_BLANK", order: 6, question: "tan²(x) + 1 = ___" },

      { id: 79, lessonId: 30, type: "SELECT", order: 1, question: "Résous : sin(x) = 1/2 sur [0, 2π]" },
      { id: 80, lessonId: 30, type: "SELECT", order: 2, question: "Résous : cos(x) = -1 sur [0, 2π]" },
      { id: 81, lessonId: 30, type: "SELECT", order: 3, question: "Résous : tan(x) = 1 sur [0, π]" },

      { id: 82, lessonId: 31, type: "SELECT", order: 1, question: "Développe : sin(a + b)" },
      { id: 83, lessonId: 31, type: "SELECT", order: 2, question: "Développe : cos(a - b)" },
      { id: 84, lessonId: 31, type: "SELECT", order: 3, question: "Calcule sin(75°) en utilisant sin(45° + 30°)" },

      { id: 85, lessonId: 32, type: "SELECT", order: 1, question: "Calcule (2 + 3i) + (1 - 5i)" },
      { id: 86, lessonId: 32, type: "SELECT", order: 2, question: "Calcule (1 + 2i)(3 - i)" },
      { id: 87, lessonId: 32, type: "SELECT", order: 3, question: "Calcule (2 + i) / (1 - i)" },
      { id: 88, lessonId: 32, type: "SELECT", order: 4, question: "Quel est le conjugué de z = 4 - 7i ?" },

      { id: 89, lessonId: 33, type: "SELECT", order: 1, question: "Quel est le module de z = 3 + 4i ?" },
      { id: 90, lessonId: 33, type: "SELECT", order: 2, question: "Quel est le module de z = -5 + 12i ?" },
      { id: 91, lessonId: 33, type: "SELECT", order: 3, question: "Quel est l'argument de z = 1 + i ?" },

      { id: 92, lessonId: 34, type: "SELECT", order: 1, question: "Écris z = 1 + i sous forme trigonométrique" },
      { id: 93, lessonId: 34, type: "SELECT", order: 2, question: "Calcule z³ pour z = √2 · e^(iπ/4)" },

      { id: 94, lessonId: 35, type: "SELECT", order: 1, question: "A = [[1,2],[3,4]], B = [[5,6],[7,8]]. Calcule A + B." },
      { id: 95, lessonId: 35, type: "SELECT", order: 2, question: "A = [[1,2],[3,4]], B = [[2,0],[1,3]]. Calcule A × B." },
      { id: 96, lessonId: 35, type: "SELECT", order: 3, question: "Calcule 2 × [[1,3],[2,5]]" },

      { id: 97, lessonId: 36, type: "SELECT", order: 1, question: "Calcule det([[2,3],[1,4]])" },
      { id: 98, lessonId: 36, type: "SELECT", order: 2, question: "Calcule det([[1,2],[3,4]])" },
      { id: 99, lessonId: 36, type: "SELECT", order: 3, question: "Quelle est l'inverse de A = [[4,7],[2,6]] ?" },

      { id: 100, lessonId: 37, type: "SELECT", order: 1, question: "Résous par Gauss : x + y + z = 6, 2x - y + z = 3, x + 2y - z = 2" },
      { id: 101, lessonId: 37, type: "SELECT", order: 2, question: "Résous par Gauss : x + 2y = 5, 3x - y = 1" },
    ]);

    await db.insert(schema.challengeOptions).values([
      { challengeId: 1, correct: false, text: "x = 6", audioSrc: "/6.mp3" },
      { challengeId: 1, correct: true, text: "x = 8", audioSrc: "/8.mp3" },
      { challengeId: 1, correct: false, text: "x = 10", audioSrc: "/10.mp3" },
      { challengeId: 2, correct: false, text: "x = 9", audioSrc: "/9.mp3" },
      { challengeId: 2, correct: false, text: "x = 13", audioSrc: "/13.mp3" },
      { challengeId: 2, correct: true, text: "x = 11", audioSrc: "/11.mp3" },
      { challengeId: 3, correct: true, text: "x = 12", audioSrc: "/12.mp3" },
      { challengeId: 3, correct: false, text: "x = 8", audioSrc: "/8.mp3" },
      { challengeId: 3, correct: false, text: "x = 14", audioSrc: "/14.mp3" },
      { challengeId: 4, correct: false, text: "x = 5", audioSrc: "/5.mp3" },
      { challengeId: 4, correct: true, text: "x = 7", audioSrc: "/7.mp3" },
      { challengeId: 4, correct: false, text: "x = 9", audioSrc: "/9.mp3" },
      { challengeId: 5, correct: false, text: "x = 6 ou x = -6" },
      { challengeId: 5, correct: false, text: "x = 9 ou x = -9" },
      { challengeId: 5, correct: true, text: "x = 3 ou x = -3" },
      { challengeId: 6, correct: true, text: "x = 3 ou x = -3" },
      { challengeId: 6, correct: false, text: "x = 9 ou x = -9" },
      { challengeId: 7, correct: false, text: "x = -4 ou x = 3" },
      { challengeId: 7, correct: true, text: "x = 4 ou x = -3" },
      { challengeId: 8, correct: false, text: "x = 7 ou x = -11" },
      { challengeId: 8, correct: true, text: "x = 5 ou x = -9" },
      { challengeId: 9, correct: true, text: "x = 2 ou x = 3" },
      { challengeId: 9, correct: false, text: "x = 1 ou x = 4" },
      { challengeId: 10, correct: false, text: "x = 8, y = 2" },
      { challengeId: 10, correct: true, text: "x = 7, y = 3" },
      { challengeId: 11, correct: false, text: "x = 2, y = 4" },
      { challengeId: 11, correct: true, text: "x = 3, y = 1" },
      { challengeId: 12, correct: true, text: "x = 2, y = 3" },
      { challengeId: 12, correct: false, text: "x = 1, y = 4" },
      { challengeId: 13, correct: false, text: "x = 3, y = 2" },
      { challengeId: 13, correct: true, text: "x = 2, y = 3" },
      { challengeId: 14, correct: false, text: "1/2" },
      { challengeId: 14, correct: true, text: "2/3" },
      { challengeId: 14, correct: false, text: "3/4" },
      { challengeId: 15, correct: false, text: "1/2" },
      { challengeId: 15, correct: false, text: "3/5" },
      { challengeId: 15, correct: true, text: "2/3" },
      { challengeId: 16, correct: false, text: "1/4" },
      { challengeId: 16, correct: true, text: "1/3" },
      { challengeId: 16, correct: false, text: "2/5" },
      { challengeId: 17, correct: false, text: "1/2" },
      { challengeId: 17, correct: false, text: "3/7" },
      { challengeId: 17, correct: true, text: "2/3" },
      { challengeId: 18, correct: false, text: "2/5" },
      { challengeId: 18, correct: true, text: "5/6" },
      { challengeId: 18, correct: false, text: "1/6" },
      { challengeId: 19, correct: false, text: "1/4" },
      { challengeId: 19, correct: false, text: "2/3" },
      { challengeId: 19, correct: true, text: "7/12" },
      { challengeId: 20, correct: false, text: "5/12" },
      { challengeId: 20, correct: true, text: "1/2" },
      { challengeId: 20, correct: false, text: "3/4" },
      { challengeId: 21, correct: false, text: "25/18" },
      { challengeId: 21, correct: false, text: "5/9" },
      { challengeId: 21, correct: true, text: "1/2" },
      { challengeId: 22, correct: false, text: "12€" },
      { challengeId: 22, correct: false, text: "16€" },
      { challengeId: 22, correct: true, text: "14€" },
      { challengeId: 23, correct: false, text: "300 km" },
      { challengeId: 23, correct: true, text: "375 km" },
      { challengeId: 23, correct: false, text: "400 km" },
      { challengeId: 24, correct: false, text: "6 ouvriers" },
      { challengeId: 24, correct: true, text: "8 ouvriers" },
      { challengeId: 24, correct: false, text: "10 ouvriers" },
      { challengeId: 25, correct: false, text: "20 cm²" },
      { challengeId: 25, correct: true, text: "24 cm²" },
      { challengeId: 25, correct: false, text: "28 cm²" },
      { challengeId: 26, correct: false, text: "15 cm" },
      { challengeId: 26, correct: true, text: "20 cm" },
      { challengeId: 26, correct: false, text: "25 cm" },
      { challengeId: 27, correct: false, text: "16 cm²" },
      { challengeId: 27, correct: true, text: "20 cm²" },
      { challengeId: 27, correct: false, text: "24 cm²" },
      { challengeId: 28, correct: false, text: "143.07 cm²" },
      { challengeId: 28, correct: true, text: "153.86 cm²" },
      { challengeId: 28, correct: false, text: "163.28 cm²" },
      { challengeId: 29, correct: false, text: "c = 6" },
      { challengeId: 29, correct: true, text: "c = 5" },
      { challengeId: 29, correct: false, text: "c = 7" },
      { challengeId: 30, correct: false, text: "c = 11" },
      { challengeId: 30, correct: true, text: "c = 13" },
      { challengeId: 30, correct: false, text: "c = 15" },
      { challengeId: 31, correct: false, text: "b = 6" },
      { challengeId: 31, correct: true, text: "b = 8" },
      { challengeId: 31, correct: false, text: "b = 10" },
      { challengeId: 32, correct: false, text: "AE = 5" },
      { challengeId: 32, correct: true, text: "AE = 6" },
      { challengeId: 32, correct: false, text: "AE = 7" },
      { challengeId: 33, correct: true, text: "BC = 6" },
      { challengeId: 33, correct: false, text: "BC = 8" },
      { challengeId: 34, correct: false, text: "5" },
      { challengeId: 34, correct: true, text: "6" },
      { challengeId: 34, correct: false, text: "7" },
      { challengeId: 35, correct: false, text: "3" },
      { challengeId: 35, correct: true, text: "5" },
      { challengeId: 35, correct: false, text: "7" },
      { challengeId: 36, correct: false, text: "10" },
      { challengeId: 36, correct: true, text: "12" },
      { challengeId: 36, correct: false, text: "14" },
      { challengeId: 37, correct: false, text: "1/3" },
      { challengeId: 37, correct: true, text: "1/6" },
      { challengeId: 37, correct: false, text: "1/12" },
      { challengeId: 38, correct: true, text: "1/13" },
      { challengeId: 38, correct: false, text: "4/52" },
      { challengeId: 39, correct: false, text: "1/2" },
      { challengeId: 39, correct: true, text: "1/4" },
      { challengeId: 39, correct: false, text: "1/3" },
      { challengeId: 60, correct: false, text: "3x² + 4x + 5" },
      { challengeId: 60, correct: true, text: "3x² + 4x - 5" },
      { challengeId: 60, correct: false, text: "x² + 4x - 5" },
      { challengeId: 61, correct: false, text: "-cos(x) + sin(x)" },
      { challengeId: 61, correct: true, text: "cos(x) - sin(x)" },
      { challengeId: 61, correct: false, text: "cos(x) + sin(x)" },
      { challengeId: 62, correct: false, text: "2x · eˣ" },
      { challengeId: 62, correct: true, text: "eˣ(x² + 2x)" },
      { challengeId: 62, correct: false, text: "eˣ · x²" },
      { challengeId: 63, correct: false, text: "1/x²" },
      { challengeId: 63, correct: true, text: "(1 - ln(x)) / x²" },
      { challengeId: 63, correct: false, text: "(1 + ln(x)) / x²" },
      { challengeId: 64, correct: false, text: "4(3x²+1)³" },
      { challengeId: 64, correct: true, text: "24x(3x²+1)³" },
      { challengeId: 64, correct: false, text: "12x(3x²+1)³" },
      { challengeId: 65, correct: false, text: "cos(2x+1)" },
      { challengeId: 65, correct: true, text: "2cos(2x+1)" },
      { challengeId: 65, correct: false, text: "-2sin(2x+1)" },
      { challengeId: 66, correct: false, text: "e^(x²-1)" },
      { challengeId: 66, correct: true, text: "2x · e^(x²-1)" },
      { challengeId: 66, correct: false, text: "x² · e^(x²-1)" },
      { challengeId: 67, correct: false, text: "1/cos(x)" },
      { challengeId: 67, correct: true, text: "-tan(x)" },
      { challengeId: 67, correct: false, text: "tan(x)" },
      { challengeId: 68, correct: false, text: "4/3" },
      { challengeId: 68, correct: true, text: "8/3" },
      { challengeId: 68, correct: false, text: "3" },
      { challengeId: 69, correct: false, text: "10" },
      { challengeId: 69, correct: true, text: "12" },
      { challengeId: 69, correct: false, text: "14" },
      { challengeId: 70, correct: false, text: "0" },
      { challengeId: 70, correct: true, text: "2" },
      { challengeId: 70, correct: false, text: "π" },
      { challengeId: 71, correct: false, text: "0" },
      { challengeId: 71, correct: true, text: "1" },
      { challengeId: 71, correct: false, text: "e" },
      { challengeId: 72, correct: false, text: "6x + 2" },
      { challengeId: 72, correct: true, text: "x³ + x²" },
      { challengeId: 72, correct: false, text: "3x³ + 2x²" },
      { challengeId: 73, correct: false, text: "-sin(x)" },
      { challengeId: 73, correct: true, text: "sin(x)" },
      { challengeId: 73, correct: false, text: "cos(x)" },
      { challengeId: 74, correct: false, text: "-1/(x+1)²" },
      { challengeId: 74, correct: true, text: "ln|x+1|" },
      { challengeId: 74, correct: false, text: "1/(x+1)²" },
      { challengeId: 75, correct: false, text: "0" },
      { challengeId: 75, correct: true, text: "1" },
      { challengeId: 75, correct: false, text: "2" },
      { challengeId: 76, correct: false, text: "1 + 2sin²(x)" },
      { challengeId: 76, correct: true, text: "1 - 2sin²(x)" },
      { challengeId: 76, correct: false, text: "2sin²(x)" },
      { challengeId: 77, correct: false, text: "cos(x)" },
      { challengeId: 77, correct: true, text: "sin(x)" },
      { challengeId: 77, correct: false, text: "tan(x)" },
      { challengeId: 78, correct: false, text: "cos²(x)" },
      { challengeId: 78, correct: true, text: "1/cos²(x)" },
      { challengeId: 78, correct: false, text: "sin²(x)" },
      { challengeId: 79, correct: false, text: "x = π/6 uniquement" },
      { challengeId: 79, correct: true, text: "x = π/6 et x = 5π/6" },
      { challengeId: 79, correct: false, text: "x = π/3 et x = 2π/3" },
      { challengeId: 80, correct: false, text: "x = π/2" },
      { challengeId: 80, correct: true, text: "x = π" },
      { challengeId: 80, correct: false, text: "x = 3π/2" },
      { challengeId: 81, correct: false, text: "x = π/3" },
      { challengeId: 81, correct: true, text: "x = π/4" },
      { challengeId: 81, correct: false, text: "x = π/6" },
      { challengeId: 82, correct: false, text: "sin(a)sin(b) + cos(a)cos(b)" },
      { challengeId: 82, correct: true, text: "sin(a)cos(b) + cos(a)sin(b)" },
      { challengeId: 82, correct: false, text: "sin(a)cos(b) - cos(a)sin(b)" },
      { challengeId: 83, correct: false, text: "cos(a)cos(b) - sin(a)sin(b)" },
      { challengeId: 83, correct: true, text: "cos(a)cos(b) + sin(a)sin(b)" },
      { challengeId: 83, correct: false, text: "sin(a)sin(b) - cos(a)cos(b)" },
      { challengeId: 84, correct: false, text: "(√6 - √2) / 4" },
      { challengeId: 84, correct: true, text: "(√6 + √2) / 4" },
      { challengeId: 84, correct: false, text: "(√3 + 1) / 4" },
      { challengeId: 85, correct: false, text: "3 + 8i" },
      { challengeId: 85, correct: true, text: "3 - 2i" },
      { challengeId: 85, correct: false, text: "1 - 2i" },
      { challengeId: 86, correct: false, text: "3 - 2i" },
      { challengeId: 86, correct: true, text: "5 + 5i" },
      { challengeId: 86, correct: false, text: "3 + 5i" },
      { challengeId: 87, correct: false, text: "1 + i" },
      { challengeId: 87, correct: true, text: "1/2 + 3i/2" },
      { challengeId: 87, correct: false, text: "2 - i" },
      { challengeId: 88, correct: false, text: "-4 + 7i" },
      { challengeId: 88, correct: true, text: "4 + 7i" },
      { challengeId: 88, correct: false, text: "-4 - 7i" },
      { challengeId: 89, correct: false, text: "7" },
      { challengeId: 89, correct: true, text: "5" },
      { challengeId: 89, correct: false, text: "√7" },
      { challengeId: 90, correct: false, text: "7" },
      { challengeId: 90, correct: true, text: "13" },
      { challengeId: 90, correct: false, text: "17" },
      { challengeId: 91, correct: false, text: "π/6" },
      { challengeId: 91, correct: true, text: "π/4" },
      { challengeId: 91, correct: false, text: "π/3" },
      { challengeId: 92, correct: false, text: "√2 · e^(iπ/6)" },
      { challengeId: 92, correct: true, text: "√2 · e^(iπ/4)" },
      { challengeId: 92, correct: false, text: "2 · e^(iπ/4)" },
      { challengeId: 93, correct: false, text: "2√2 · e^(iπ/4)" },
      { challengeId: 93, correct: true, text: "2√2 · e^(i3π/4)" },
      { challengeId: 93, correct: false, text: "√2 · e^(i3π/4)" },
      { challengeId: 94, correct: false, text: "[[5,8],[10,12]]" },
      { challengeId: 94, correct: true, text: "[[6,8],[10,12]]" },
      { challengeId: 94, correct: false, text: "[[6,8],[9,12]]" },
      { challengeId: 95, correct: false, text: "[[3,6],[13,12]]" },
      { challengeId: 95, correct: true, text: "[[4,6],[14,12]]" },
      { challengeId: 95, correct: false, text: "[[4,6],[13,12]]" },
      { challengeId: 96, correct: false, text: "[[1,3],[2,5]]" },
      { challengeId: 96, correct: true, text: "[[2,6],[4,10]]" },
      { challengeId: 96, correct: false, text: "[[2,6],[4,5]]" },
      { challengeId: 97, correct: false, text: "11" },
      { challengeId: 97, correct: true, text: "5" },
      { challengeId: 97, correct: false, text: "8" },
      { challengeId: 98, correct: false, text: "2" },
      { challengeId: 98, correct: true, text: "-2" },
      { challengeId: 98, correct: false, text: "10" },
      { challengeId: 99, correct: true, text: "[[6,-7],[-2,4]] / 10" },
      { challengeId: 99, correct: false, text: "[[4,-3],[-2,6]] / 10" },
      { challengeId: 99, correct: false, text: "[[6,7],[2,4]] / 10" },
      { challengeId: 100, correct: true, text: "x=1, y=2, z=3" },
      { challengeId: 100, correct: false, text: "x=2, y=1, z=3" },
      { challengeId: 100, correct: false, text: "x=3, y=1, z=2" },
      { challengeId: 101, correct: true, text: "x=1, y=2" },
      { challengeId: 101, correct: false, text: "x=0, y=2" },
      { challengeId: 101, correct: false, text: "x=2, y=1" },

      // ── FILL_BLANK options ──
      { challengeId: 200, correct: true, text: "8", blank: 0 },
      { challengeId: 200, correct: false, text: "6", blank: 0 },
      { challengeId: 200, correct: false, text: "10", blank: 0 },

      { challengeId: 201, correct: true, text: "4", blank: 0 },
      { challengeId: 201, correct: false, text: "3", blank: 0 },
      { challengeId: 201, correct: false, text: "6", blank: 0 },

      { challengeId: 202, correct: true, text: "4", blank: 0 },
      { challengeId: 202, correct: false, text: "6", blank: 0 },
      { challengeId: 202, correct: false, text: "2", blank: 0 },

      { challengeId: 203, correct: true, text: "5", blank: 0 },
      { challengeId: 203, correct: true, text: "-5", blank: 1 },
      { challengeId: 203, correct: false, text: "3", blank: 0 },
      { challengeId: 203, correct: false, text: "-3", blank: 1 },
      { challengeId: 203, correct: false, text: "25", blank: 0 },

      { challengeId: 204, correct: true, text: "3", blank: 0 },
      { challengeId: 204, correct: true, text: "4", blank: 1 },
      { challengeId: 204, correct: false, text: "2", blank: 0 },
      { challengeId: 204, correct: false, text: "6", blank: 1 },
      { challengeId: 204, correct: false, text: "1", blank: 0 },

      { challengeId: 205, correct: true, text: "2/3", blank: 0 },
      { challengeId: 205, correct: false, text: "1/2", blank: 0 },
      { challengeId: 205, correct: false, text: "3/4", blank: 0 },

      { challengeId: 206, correct: true, text: "1/3", blank: 0 },
      { challengeId: 206, correct: true, text: "2/3", blank: 1 },
      { challengeId: 206, correct: false, text: "1/4", blank: 0 },
      { challengeId: 206, correct: false, text: "3/5", blank: 1 },
      { challengeId: 206, correct: false, text: "2/5", blank: 0 },

      { challengeId: 207, correct: true, text: "5/6", blank: 0 },
      { challengeId: 207, correct: false, text: "2/5", blank: 0 },
      { challengeId: 207, correct: false, text: "1/6", blank: 0 },

      { challengeId: 208, correct: true, text: "1/2", blank: 0 },
      { challengeId: 208, correct: true, text: "1/2", blank: 1 },
      { challengeId: 208, correct: false, text: "2/3", blank: 0 },
      { challengeId: 208, correct: false, text: "1/3", blank: 1 },
      { challengeId: 208, correct: false, text: "3/4", blank: 0 },

      { challengeId: 209, correct: true, text: "24", blank: 0 },
      { challengeId: 209, correct: false, text: "20", blank: 0 },
      { challengeId: 209, correct: false, text: "28", blank: 0 },

      { challengeId: 210, correct: true, text: "20", blank: 0 },
      { challengeId: 210, correct: false, text: "15", blank: 0 },
      { challengeId: 210, correct: false, text: "25", blank: 0 },

      { challengeId: 211, correct: true, text: "5", blank: 0 },
      { challengeId: 211, correct: false, text: "6", blank: 0 },
      { challengeId: 211, correct: false, text: "7", blank: 0 },

      { challengeId: 212, correct: true, text: "13", blank: 0 },
      { challengeId: 212, correct: false, text: "11", blank: 0 },
      { challengeId: 212, correct: false, text: "15", blank: 0 },

      { challengeId: 213, correct: true, text: "6", blank: 0 },
      { challengeId: 213, correct: false, text: "5", blank: 0 },
      { challengeId: 213, correct: false, text: "7", blank: 0 },

      { challengeId: 214, correct: true, text: "5", blank: 0 },
      { challengeId: 214, correct: false, text: "3", blank: 0 },
      { challengeId: 214, correct: false, text: "7", blank: 0 },

      { challengeId: 215, correct: true, text: "3x²", blank: 0 },
      { challengeId: 215, correct: true, text: "4x³", blank: 1 },
      { challengeId: 215, correct: false, text: "2x", blank: 0 },
      { challengeId: 215, correct: false, text: "3x²", blank: 1 },
      { challengeId: 215, correct: false, text: "x²", blank: 0 },

      { challengeId: 216, correct: true, text: "cos(x)", blank: 0 },
      { challengeId: 216, correct: true, text: "-sin(x)", blank: 1 },
      { challengeId: 216, correct: false, text: "-cos(x)", blank: 0 },
      { challengeId: 216, correct: false, text: "sin(x)", blank: 1 },
      { challengeId: 216, correct: false, text: "tan(x)", blank: 0 },

      { challengeId: 217, correct: true, text: "1", blank: 0 },
      { challengeId: 217, correct: false, text: "0", blank: 0 },
      { challengeId: 217, correct: false, text: "2", blank: 0 },

      { challengeId: 218, correct: true, text: "1/cos²(x)", blank: 0 },
      { challengeId: 218, correct: false, text: "cos²(x)", blank: 0 },
      { challengeId: 218, correct: false, text: "sin²(x)", blank: 0 },
    ]);

    // ================================================
    // 2. ESPAGNOL (Course ID: 2)
    // ================================================

    await db.insert(schema.units).values([
      { id: 5, courseId: 2, title: "Introducción", description: "Learn the basics of Spanish", order: 1 },
      { id: 6, courseId: 2, title: "Familia y Amigos", description: "Talk about family and friends", order: 2 },
      { id: 7, courseId: 2, title: "Comida y Bebida", description: "Food and drinks vocabulary", order: 3 },
    ]);

    await db.insert(schema.lessons).values([
      { id: 12, unitId: 5, order: 1, title: "Nouns & Articles" },
      { id: 13, unitId: 5, order: 2, title: "Basic Verbs" },
      { id: 14, unitId: 5, order: 3, title: "Greetings" },
      { id: 15, unitId: 6, order: 1, title: "Family Members" },
      { id: 16, unitId: 6, order: 2, title: "Adjectives" },
      { id: 17, unitId: 7, order: 1, title: "Food" },
      { id: 18, unitId: 7, order: 2, title: "Drinks" },
    ]);

    await db.insert(schema.challenges).values([
      { id: 40, lessonId: 12, type: "SELECT", order: 1, question: 'Which one is "the man"?' },
      { id: 41, lessonId: 12, type: "ASSIST", order: 2, question: '"the man"' },
      { id: 42, lessonId: 12, type: "SELECT", order: 3, question: 'Which one is "the woman"?' },
      { id: 43, lessonId: 13, type: "ASSIST", order: 1, question: '"to speak"' },
      { id: 44, lessonId: 13, type: "ASSIST", order: 2, question: '"to eat"' },
      { id: 45, lessonId: 14, type: "SELECT", order: 1, question: 'How do you say "Hello"?' },
      { id: 46, lessonId: 15, type: "SELECT", order: 1, question: 'Which one is "mother"?' },
      { id: 47, lessonId: 16, type: "SELECT", order: 1, question: 'Which one means "big"?' },
      { id: 48, lessonId: 17, type: "SELECT", order: 1, question: 'Which one is "bread"?' },
      { id: 49, lessonId: 18, type: "SELECT", order: 1, question: 'Which one is "water"?' },
      { id: 110, lessonId: 12, type: "WORD_BANK", order: 4, question: 'Translate: "The man eats bread"' },
      { id: 111, lessonId: 13, type: "WORD_BANK", order: 3, question: 'Translate: "I want to speak Spanish"' },
      { id: 112, lessonId: 14, type: "WORD_BANK", order: 2, question: 'Translate: "Good morning, how are you?"' },
      { id: 113, lessonId: 15, type: "WORD_BANK", order: 2, question: 'Translate: "My mother is very kind"' },
      { id: 114, lessonId: 16, type: "WORD_BANK", order: 2, question: 'Translate: "The big dog is fast"' },
      { id: 115, lessonId: 17, type: "WORD_BANK", order: 2, question: 'Translate: "I eat bread with cheese"' },
      { id: 116, lessonId: 18, type: "WORD_BANK", order: 2, question: 'Translate: "She drinks water every day"' },
    ]);

    await db.insert(schema.challengeOptions).values([
      { challengeId: 40, correct: true, text: "el hombre", imageSrc: "/man.svg", audioSrc: "/es_man.mp3" },
      { challengeId: 40, correct: false, text: "la mujer", imageSrc: "/woman.svg", audioSrc: "/es_woman.mp3" },
      { challengeId: 40, correct: false, text: "el niño", imageSrc: "/boy.svg", audioSrc: "/es_boy.mp3" },
      { challengeId: 41, correct: true, text: "el hombre", imageSrc: "/man.svg", audioSrc: "/es_man.mp3" },
      { challengeId: 41, correct: false, text: "la mujer", imageSrc: "/woman.svg", audioSrc: "/es_woman.mp3" },
      { challengeId: 41, correct: false, text: "el niño", imageSrc: "/boy.svg", audioSrc: "/es_boy.mp3" },
      { challengeId: 42, correct: true, text: "la mujer", imageSrc: "/woman.svg" },
      { challengeId: 42, correct: false, text: "el hombre", imageSrc: "/man.svg" },
      { challengeId: 42, correct: false, text: "la niña", imageSrc: "/girl.svg" },
      { challengeId: 43, correct: true, text: "hablar" },
      { challengeId: 43, correct: false, text: "comer" },
      { challengeId: 43, correct: false, text: "beber" },
      { challengeId: 44, correct: true, text: "comer" },
      { challengeId: 44, correct: false, text: "hablar" },
      { challengeId: 44, correct: false, text: "vivir" },
      { challengeId: 45, correct: true, text: "Hola" },
      { challengeId: 45, correct: false, text: "Adiós" },
      { challengeId: 45, correct: false, text: "Gracias" },
      { challengeId: 46, correct: true, text: "la madre", imageSrc: "/mother.svg" },
      { challengeId: 46, correct: false, text: "el padre", imageSrc: "/father.svg" },
      { challengeId: 46, correct: false, text: "el hermano", imageSrc: "/brother.svg" },
      { challengeId: 47, correct: true, text: "grande" },
      { challengeId: 47, correct: false, text: "pequeño" },
      { challengeId: 47, correct: false, text: "rápido" },
      { challengeId: 48, correct: true, text: "el pan", imageSrc: "/bread.svg" },
      { challengeId: 48, correct: false, text: "el queso", imageSrc: "/cheese.svg" },
      { challengeId: 48, correct: false, text: "la carne", imageSrc: "/meat.svg" },
      { challengeId: 49, correct: true, text: "el agua", imageSrc: "/water.svg" },
      { challengeId: 49, correct: false, text: "el vino", imageSrc: "/wine.svg" },
      { challengeId: 49, correct: false, text: "la cerveza", imageSrc: "/beer.svg" },
      { challengeId: 110, correct: true, text: "El", order: 1 },
      { challengeId: 110, correct: true, text: "hombre", order: 2 },
      { challengeId: 110, correct: true, text: "come", order: 3 },
      { challengeId: 110, correct: true, text: "pan", order: 4 },
      { challengeId: 110, correct: false, text: "bebe", order: null },
      { challengeId: 110, correct: false, text: "mujer", order: null },
      { challengeId: 110, correct: false, text: "agua", order: null },
      { challengeId: 111, correct: true, text: "Quiero", order: 1 },
      { challengeId: 111, correct: true, text: "hablar", order: 2 },
      { challengeId: 111, correct: true, text: "español", order: 3 },
      { challengeId: 111, correct: false, text: "comer", order: null },
      { challengeId: 111, correct: false, text: "francés", order: null },
      { challengeId: 111, correct: false, text: "beber", order: null },
      { challengeId: 112, correct: true, text: "Buenos", order: 1 },
      { challengeId: 112, correct: true, text: "días,", order: 2 },
      { challengeId: 112, correct: true, text: "¿cómo", order: 3 },
      { challengeId: 112, correct: true, text: "estás?", order: 4 },
      { challengeId: 112, correct: false, text: "noches,", order: null },
      { challengeId: 112, correct: false, text: "tardes,", order: null },
      { challengeId: 113, correct: true, text: "Mi", order: 1 },
      { challengeId: 113, correct: true, text: "madre", order: 2 },
      { challengeId: 113, correct: true, text: "es", order: 3 },
      { challengeId: 113, correct: true, text: "muy", order: 4 },
      { challengeId: 113, correct: true, text: "amable", order: 5 },
      { challengeId: 113, correct: false, text: "padre", order: null },
      { challengeId: 113, correct: false, text: "poco", order: null },
      { challengeId: 113, correct: false, text: "rápida", order: null },
      { challengeId: 114, correct: true, text: "El", order: 1 },
      { challengeId: 114, correct: true, text: "perro", order: 2 },
      { challengeId: 114, correct: true, text: "grande", order: 3 },
      { challengeId: 114, correct: true, text: "es", order: 4 },
      { challengeId: 114, correct: true, text: "rápido", order: 5 },
      { challengeId: 114, correct: false, text: "gato", order: null },
      { challengeId: 114, correct: false, text: "pequeño", order: null },
      { challengeId: 114, correct: false, text: "lento", order: null },
      { challengeId: 115, correct: true, text: "Como", order: 1 },
      { challengeId: 115, correct: true, text: "pan", order: 2 },
      { challengeId: 115, correct: true, text: "con", order: 3 },
      { challengeId: 115, correct: true, text: "queso", order: 4 },
      { challengeId: 115, correct: false, text: "bebo", order: null },
      { challengeId: 115, correct: false, text: "agua", order: null },
      { challengeId: 115, correct: false, text: "carne", order: null },
      { challengeId: 116, correct: true, text: "Ella", order: 1 },
      { challengeId: 116, correct: true, text: "bebe", order: 2 },
      { challengeId: 116, correct: true, text: "agua", order: 3 },
      { challengeId: 116, correct: true, text: "todos", order: 4 },
      { challengeId: 116, correct: true, text: "los", order: 5 },
      { challengeId: 116, correct: true, text: "días", order: 6 },
      { challengeId: 116, correct: false, text: "come", order: null },
      { challengeId: 116, correct: false, text: "vino", order: null },
      { challengeId: 116, correct: false, text: "nunca", order: null },
    ]);

    // ================================================
    // 3. ITALIEN (Course ID: 3)
    // ================================================

    await db.insert(schema.units).values([
      { id: 8, courseId: 3, title: "Introduzione", description: "Learn the basics of Italian", order: 1 },
    ]);

    await db.insert(schema.lessons).values([
      { id: 19, unitId: 8, order: 1, title: "Nouns" },
      { id: 20, unitId: 8, order: 2, title: "Greetings" },
    ]);

    await db.insert(schema.challenges).values([
      { id: 120, lessonId: 19, type: "SELECT", order: 1, question: 'Which one is "the cat"?' },
      { id: 121, lessonId: 19, type: "SELECT", order: 2, question: 'Which one is "the dog"?' },
      { id: 122, lessonId: 19, type: "WORD_BANK", order: 3, question: 'Translate: "The cat drinks milk"' },
      { id: 123, lessonId: 20, type: "SELECT", order: 1, question: 'How do you say "Good morning"?' },
      { id: 124, lessonId: 20, type: "WORD_BANK", order: 2, question: 'Translate: "Hello, my name is Marco"' },
    ]);

    await db.insert(schema.challengeOptions).values([
      { challengeId: 120, correct: true, text: "il gatto", imageSrc: "/cat.svg" },
      { challengeId: 120, correct: false, text: "il cane", imageSrc: "/dog.svg" },
      { challengeId: 120, correct: false, text: "il topo", imageSrc: "/mouse.svg" },
      { challengeId: 121, correct: true, text: "il cane", imageSrc: "/dog.svg" },
      { challengeId: 121, correct: false, text: "il gatto", imageSrc: "/cat.svg" },
      { challengeId: 121, correct: false, text: "l'uccello", imageSrc: "/bird.svg" },
      { challengeId: 122, correct: true, text: "Il", order: 1 },
      { challengeId: 122, correct: true, text: "gatto", order: 2 },
      { challengeId: 122, correct: true, text: "beve", order: 3 },
      { challengeId: 122, correct: true, text: "latte", order: 4 },
      { challengeId: 122, correct: false, text: "cane", order: null },
      { challengeId: 122, correct: false, text: "mangia", order: null },
      { challengeId: 122, correct: false, text: "acqua", order: null },
      { challengeId: 123, correct: true, text: "Buongiorno" },
      { challengeId: 123, correct: false, text: "Buonasera" },
      { challengeId: 123, correct: false, text: "Buonanotte" },
      { challengeId: 124, correct: true, text: "Ciao,", order: 1 },
      { challengeId: 124, correct: true, text: "mi", order: 2 },
      { challengeId: 124, correct: true, text: "chiamo", order: 3 },
      { challengeId: 124, correct: true, text: "Marco", order: 4 },
      { challengeId: 124, correct: false, text: "sono", order: null },
      { challengeId: 124, correct: false, text: "Luca", order: null },
    ]);

    // ================================================
    // 4. FRANÇAIS (Course ID: 4)
    // ================================================

    await db.insert(schema.units).values([
      { id: 9, courseId: 4, title: "Introduction", description: "Learn the basics of French", order: 1 },
      { id: 21, courseId: 4, title: "La Vie Quotidienne", description: "La vie de tous les jours", order: 2 },
    ]);

    await db.insert(schema.lessons).values([
      { id: 21, unitId: 9, order: 1, title: "Nouns" },
      { id: 22, unitId: 9, order: 2, title: "Greetings" },
      { id: 62, unitId: 21, order: 1, title: "Les Animaux" },
      { id: 63, unitId: 21, order: 2, title: "La Famille" },
      { id: 64, unitId: 21, order: 3, title: "Les Couleurs" },
    ]);

    await db.insert(schema.challenges).values([
      { id: 130, lessonId: 21, type: "SELECT", order: 1, question: 'Which one is "the book"?' },
      { id: 131, lessonId: 21, type: "SELECT", order: 2, question: 'Which one is "the table"?' },
      { id: 132, lessonId: 21, type: "WORD_BANK", order: 3, question: 'Translate: "The book is on the table"' },
      { id: 133, lessonId: 22, type: "SELECT", order: 1, question: 'How do you say "Good evening"?' },
      { id: 134, lessonId: 22, type: "WORD_BANK", order: 2, question: 'Translate: "Hello, how are you today?"' },
      { id: 135, lessonId: 22, type: "WORD_BANK", order: 3, question: 'Translate: "My name is Paul, I am French"' },
      { id: 136, lessonId: 62, type: "SELECT", order: 1, question: 'Which one is "the cat"?' },
      { id: 137, lessonId: 62, type: "SELECT", order: 2, question: 'Which one is "the dog"?' },
      { id: 138, lessonId: 62, type: "WORD_BANK", order: 3, question: 'Translate: "The dog runs in the garden"' },
      { id: 139, lessonId: 62, type: "WORD_BANK", order: 4, question: 'Translate: "My cat is black and white"' },
      { id: 140, lessonId: 63, type: "SELECT", order: 1, question: 'Which one is "the father"?' },
      { id: 141, lessonId: 63, type: "WORD_BANK", order: 2, question: 'Translate: "My brother is tall and kind"' },
      { id: 142, lessonId: 63, type: "WORD_BANK", order: 3, question: 'Translate: "She has two sisters and one brother"' },
      { id: 143, lessonId: 64, type: "SELECT", order: 1, question: 'Which one means "red"?' },
      { id: 144, lessonId: 64, type: "WORD_BANK", order: 2, question: 'Translate: "The sky is blue and the grass is green"' },
      { id: 145, lessonId: 64, type: "WORD_BANK", order: 3, question: 'Translate: "I like the red car"' },
    ]);

    await db.insert(schema.challengeOptions).values([
      { challengeId: 130, correct: true, text: "le livre", imageSrc: "/book.svg" },
      { challengeId: 130, correct: false, text: "la chaise", imageSrc: "/chair.svg" },
      { challengeId: 130, correct: false, text: "la fenêtre", imageSrc: "/window.svg" },
      { challengeId: 131, correct: true, text: "la table", imageSrc: "/table.svg" },
      { challengeId: 131, correct: false, text: "le livre", imageSrc: "/book.svg" },
      { challengeId: 131, correct: false, text: "la chaise", imageSrc: "/chair.svg" },
      { challengeId: 132, correct: true, text: "Le", order: 1 },
      { challengeId: 132, correct: true, text: "livre", order: 2 },
      { challengeId: 132, correct: true, text: "est", order: 3 },
      { challengeId: 132, correct: true, text: "sur", order: 4 },
      { challengeId: 132, correct: true, text: "la", order: 5 },
      { challengeId: 132, correct: true, text: "table", order: 6 },
      { challengeId: 132, correct: false, text: "sous", order: null },
      { challengeId: 132, correct: false, text: "chaise", order: null },
      { challengeId: 133, correct: true, text: "Bonsoir" },
      { challengeId: 133, correct: false, text: "Bonjour" },
      { challengeId: 133, correct: false, text: "Bonne nuit" },
      { challengeId: 134, correct: true, text: "Bonjour,", order: 1 },
      { challengeId: 134, correct: true, text: "comment", order: 2 },
      { challengeId: 134, correct: true, text: "allez-vous", order: 3 },
      { challengeId: 134, correct: true, text: "aujourd'hui", order: 4 },
      { challengeId: 134, correct: false, text: "Bonsoir,", order: null },
      { challengeId: 134, correct: false, text: "demain", order: null },
      { challengeId: 134, correct: false, text: "hier", order: null },
      { challengeId: 135, correct: true, text: "Je", order: 1 },
      { challengeId: 135, correct: true, text: "m'appelle", order: 2 },
      { challengeId: 135, correct: true, text: "Paul,", order: 3 },
      { challengeId: 135, correct: true, text: "je", order: 4 },
      { challengeId: 135, correct: true, text: "suis", order: 5 },
      { challengeId: 135, correct: true, text: "français", order: 6 },
      { challengeId: 135, correct: false, text: "Marie,", order: null },
      { challengeId: 135, correct: false, text: "anglais", order: null },
      { challengeId: 136, correct: true, text: "le chat", imageSrc: "/cat.svg" },
      { challengeId: 136, correct: false, text: "le chien", imageSrc: "/dog.svg" },
      { challengeId: 136, correct: false, text: "le lapin", imageSrc: "/rabbit.svg" },
      { challengeId: 137, correct: true, text: "le chien", imageSrc: "/dog.svg" },
      { challengeId: 137, correct: false, text: "le chat", imageSrc: "/cat.svg" },
      { challengeId: 137, correct: false, text: "l'oiseau", imageSrc: "/bird.svg" },
      { challengeId: 138, correct: true, text: "Le", order: 1 },
      { challengeId: 138, correct: true, text: "chien", order: 2 },
      { challengeId: 138, correct: true, text: "court", order: 3 },
      { challengeId: 138, correct: true, text: "dans", order: 4 },
      { challengeId: 138, correct: true, text: "le", order: 5 },
      { challengeId: 138, correct: true, text: "jardin", order: 6 },
      { challengeId: 138, correct: false, text: "chat", order: null },
      { challengeId: 138, correct: false, text: "marche", order: null },
      { challengeId: 138, correct: false, text: "maison", order: null },
      { challengeId: 139, correct: true, text: "Mon", order: 1 },
      { challengeId: 139, correct: true, text: "chat", order: 2 },
      { challengeId: 139, correct: true, text: "est", order: 3 },
      { challengeId: 139, correct: true, text: "noir", order: 4 },
      { challengeId: 139, correct: true, text: "et", order: 5 },
      { challengeId: 139, correct: true, text: "blanc", order: 6 },
      { challengeId: 139, correct: false, text: "chien", order: null },
      { challengeId: 139, correct: false, text: "rouge", order: null },
      { challengeId: 140, correct: true, text: "le père", imageSrc: "/father.svg" },
      { challengeId: 140, correct: false, text: "la mère", imageSrc: "/mother.svg" },
      { challengeId: 140, correct: false, text: "le frère", imageSrc: "/brother.svg" },
      { challengeId: 141, correct: true, text: "Mon", order: 1 },
      { challengeId: 141, correct: true, text: "frère", order: 2 },
      { challengeId: 141, correct: true, text: "est", order: 3 },
      { challengeId: 141, correct: true, text: "grand", order: 4 },
      { challengeId: 141, correct: true, text: "et", order: 5 },
      { challengeId: 141, correct: true, text: "gentil", order: 6 },
      { challengeId: 141, correct: false, text: "sœur", order: null },
      { challengeId: 141, correct: false, text: "petit", order: null },
      { challengeId: 141, correct: false, text: "méchant", order: null },
      { challengeId: 142, correct: true, text: "Elle", order: 1 },
      { challengeId: 142, correct: true, text: "a", order: 2 },
      { challengeId: 142, correct: true, text: "deux", order: 3 },
      { challengeId: 142, correct: true, text: "sœurs", order: 4 },
      { challengeId: 142, correct: true, text: "et", order: 5 },
      { challengeId: 142, correct: true, text: "un", order: 6 },
      { challengeId: 142, correct: true, text: "frère", order: 7 },
      { challengeId: 142, correct: false, text: "Il", order: null },
      { challengeId: 142, correct: false, text: "trois", order: null },
      { challengeId: 142, correct: false, text: "cousins", order: null },
      { challengeId: 143, correct: true, text: "rouge" },
      { challengeId: 143, correct: false, text: "bleu" },
      { challengeId: 143, correct: false, text: "vert" },
      { challengeId: 144, correct: true, text: "Le", order: 1 },
      { challengeId: 144, correct: true, text: "ciel", order: 2 },
      { challengeId: 144, correct: true, text: "est", order: 3 },
      { challengeId: 144, correct: true, text: "bleu", order: 4 },
      { challengeId: 144, correct: true, text: "et", order: 5 },
      { challengeId: 144, correct: true, text: "l'herbe", order: 6 },
      { challengeId: 144, correct: true, text: "est", order: 7 },
      { challengeId: 144, correct: true, text: "verte", order: 8 },
      { challengeId: 144, correct: false, text: "rouge", order: null },
      { challengeId: 144, correct: false, text: "nuage", order: null },
      { challengeId: 144, correct: false, text: "jaune", order: null },
      { challengeId: 145, correct: true, text: "J'aime", order: 1 },
      { challengeId: 145, correct: true, text: "la", order: 2 },
      { challengeId: 145, correct: true, text: "voiture", order: 3 },
      { challengeId: 145, correct: true, text: "rouge", order: 4 },
      { challengeId: 145, correct: false, text: "bleue", order: null },
      { challengeId: 145, correct: false, text: "moto", order: null },
      { challengeId: 145, correct: false, text: "verte", order: null },
    ]);

    // ================================================
    // 5. CROATE (Course ID: 5)
    // ================================================

    await db.insert(schema.units).values([
      { id: 10, courseId: 5, title: "Uvod", description: "Learn the basics of Croatian", order: 1 },
    ]);

    await db.insert(schema.lessons).values([
      { id: 23, unitId: 10, order: 1, title: "Nouns" },
      { id: 24, unitId: 10, order: 2, title: "Greetings" },
    ]);

    await db.insert(schema.challenges).values([
      { id: 150, lessonId: 23, type: "SELECT", order: 1, question: 'Which one is "the house"?' },
      { id: 151, lessonId: 23, type: "WORD_BANK", order: 2, question: 'Translate: "The house is big and beautiful"' },
      { id: 152, lessonId: 24, type: "SELECT", order: 1, question: 'How do you say "Thank you"?' },
      { id: 153, lessonId: 24, type: "WORD_BANK", order: 2, question: 'Translate: "Good morning, how are you?"' },
    ]);

    await db.insert(schema.challengeOptions).values([
      { challengeId: 150, correct: true, text: "kuća", imageSrc: "/house.svg" },
      { challengeId: 150, correct: false, text: "auto", imageSrc: "/car.svg" },
      { challengeId: 150, correct: false, text: "pas", imageSrc: "/dog.svg" },
      { challengeId: 151, correct: true, text: "Kuća", order: 1 },
      { challengeId: 151, correct: true, text: "je", order: 2 },
      { challengeId: 151, correct: true, text: "velika", order: 3 },
      { challengeId: 151, correct: true, text: "i", order: 4 },
      { challengeId: 151, correct: true, text: "lijepa", order: 5 },
      { challengeId: 151, correct: false, text: "mala", order: null },
      { challengeId: 151, correct: false, text: "auto", order: null },
      { challengeId: 152, correct: true, text: "Hvala" },
      { challengeId: 152, correct: false, text: "Molim" },
      { challengeId: 152, correct: false, text: "Dobar dan" },
      { challengeId: 153, correct: true, text: "Dobro", order: 1 },
      { challengeId: 153, correct: true, text: "jutro,", order: 2 },
      { challengeId: 153, correct: true, text: "kako", order: 3 },
      { challengeId: 153, correct: true, text: "ste?", order: 4 },
      { challengeId: 153, correct: false, text: "večer,", order: null },
      { challengeId: 153, correct: false, text: "gdje", order: null },
    ]);

    // ================================================
    // 6. CULTURE GÉNÉRALE (Course ID: 6)
    // ================================================

    await db.insert(schema.units).values([
      { id: 15, courseId: 6, title: "Géographie", description: "Découvre les merveilles du monde", order: 1 },
      { id: 16, courseId: 6, title: "Histoire", description: "Les grands événements qui ont façonné notre monde", order: 2 },
      { id: 17, courseId: 6, title: "Arts & Littérature", description: "Les chefs-d'œuvre de l'humanité", order: 3 },
      { id: 18, courseId: 6, title: "Sciences & Découvertes", description: "Les avancées qui ont changé notre vie", order: 4 },
      { id: 19, courseId: 6, title: "Politique & Société", description: "Comprendre le monde d'aujourd'hui", order: 5 },
      { id: 20, courseId: 6, title: "Mythes & Légendes", description: "Les histoires qui ont traversé les âges", order: 6 },
    ]);

    await db.insert(schema.lessons).values([
      { id: 38, unitId: 15, order: 1, title: "Capitales du Monde" },
      { id: 39, unitId: 15, order: 2, title: "Les Grands Fleuves" },
      { id: 40, unitId: 15, order: 3, title: "Les Plus Hauts Sommets" },
      { id: 41, unitId: 15, order: 4, title: "Déserts et Mers" },
      { id: 42, unitId: 16, order: 1, title: "Grandes Civilisations" },
      { id: 43, unitId: 16, order: 2, title: "Personnages Historiques" },
      { id: 44, unitId: 16, order: 3, title: "Dates Clés" },
      { id: 45, unitId: 16, order: 4, title: "Inventions et Découvertes" },
      { id: 46, unitId: 17, order: 1, title: "Peintres Célèbres" },
      { id: 47, unitId: 17, order: 2, title: "Écrivains et Œuvres" },
      { id: 48, unitId: 17, order: 3, title: "Musique Classique" },
      { id: 49, unitId: 17, order: 4, title: "Cinéma et Théâtre" },
      { id: 50, unitId: 18, order: 1, title: "Physique et Chimie" },
      { id: 51, unitId: 18, order: 2, title: "Biologie et Médecine" },
      { id: 52, unitId: 18, order: 3, title: "Astronomie" },
      { id: 53, unitId: 18, order: 4, title: "Grands Scientifiques" },
      { id: 54, unitId: 19, order: 1, title: "Symboles et Institutions" },
      { id: 55, unitId: 19, order: 2, title: "Droits et Libertés" },
      { id: 56, unitId: 19, order: 3, title: "Organisations Internationales" },
      { id: 57, unitId: 19, order: 4, title: "Grands Discours" },
      { id: 58, unitId: 20, order: 1, title: "Mythologie Grecque" },
      { id: 59, unitId: 20, order: 2, title: "Mythologie Nordique" },
      { id: 60, unitId: 20, order: 3, title: "Légendes Médiévales" },
      { id: 61, unitId: 20, order: 4, title: "Folklore et Traditions" },
    ]);

    await db.insert(schema.challenges).values([
      { id: 160, lessonId: 38, type: "SELECT", order: 1, question: "Quelle est la capitale de la France ?" },
      { id: 161, lessonId: 38, type: "SELECT", order: 2, question: "Quelle est la capitale du Japon ?" },
      { id: 162, lessonId: 38, type: "SELECT", order: 3, question: "Quelle est la capitale du Brésil ?" },
      { id: 163, lessonId: 39, type: "SELECT", order: 1, question: "Quel est le plus long fleuve du monde ?" },
      { id: 164, lessonId: 39, type: "SELECT", order: 2, question: "Dans quel continent se trouve l'Amazone ?" },
      { id: 165, lessonId: 40, type: "SELECT", order: 1, question: "Quel est le plus haut sommet du monde ?" },
      { id: 166, lessonId: 40, type: "SELECT", order: 2, question: "Sur quel continent se trouve le Mont Everest ?" },
      { id: 167, lessonId: 41, type: "SELECT", order: 1, question: "Quel est le plus grand désert du monde ?" },
      { id: 168, lessonId: 42, type: "SELECT", order: 1, question: "Quelle civilisation a construit les pyramides ?" },
      { id: 169, lessonId: 43, type: "SELECT", order: 1, question: "Qui a peint la Joconde ?" },
      { id: 170, lessonId: 44, type: "SELECT", order: 1, question: "En quelle année a eu lieu la Révolution française ?" },
      { id: 171, lessonId: 45, type: "SELECT", order: 1, question: "Qui a inventé le téléphone ?" },
      { id: 172, lessonId: 46, type: "SELECT", order: 1, question: "Qui a peint La Nuit étoilée ?" },
      { id: 173, lessonId: 47, type: "SELECT", order: 1, question: "Qui a écrit Les Misérables ?" },
      { id: 174, lessonId: 50, type: "SELECT", order: 1, question: "Quelle est la formule de l'eau ?" },
      { id: 175, lessonId: 52, type: "SELECT", order: 1, question: "Quelle planète est la plus proche du Soleil ?" },
      { id: 176, lessonId: 53, type: "SELECT", order: 1, question: "Qui a découvert la pénicilline ?" },
      { id: 177, lessonId: 58, type: "SELECT", order: 1, question: "Qui est le dieu grec de la mer ?" },
      { id: 178, lessonId: 58, type: "SELECT", order: 2, question: "Qui est le dieu grec du soleil ?" },
    ]);

    await db.insert(schema.challengeOptions).values([
      { challengeId: 160, correct: true, text: "Paris" },
      { challengeId: 160, correct: false, text: "Lyon" },
      { challengeId: 160, correct: false, text: "Marseille" },
      { challengeId: 161, correct: true, text: "Tokyo" },
      { challengeId: 161, correct: false, text: "Osaka" },
      { challengeId: 161, correct: false, text: "Kyoto" },
      { challengeId: 162, correct: true, text: "Brasília" },
      { challengeId: 162, correct: false, text: "Rio de Janeiro" },
      { challengeId: 162, correct: false, text: "São Paulo" },
      { challengeId: 163, correct: true, text: "Le Nil" },
      { challengeId: 163, correct: false, text: "L'Amazone" },
      { challengeId: 163, correct: false, text: "Le Yangtsé" },
      { challengeId: 164, correct: true, text: "Amérique du Sud" },
      { challengeId: 164, correct: false, text: "Afrique" },
      { challengeId: 164, correct: false, text: "Asie" },
      { challengeId: 165, correct: true, text: "Le Mont Everest" },
      { challengeId: 165, correct: false, text: "Le K2" },
      { challengeId: 165, correct: false, text: "Le Mont Blanc" },
      { challengeId: 166, correct: true, text: "Asie" },
      { challengeId: 166, correct: false, text: "Afrique" },
      { challengeId: 166, correct: false, text: "Europe" },
      { challengeId: 167, correct: true, text: "Le Sahara" },
      { challengeId: 167, correct: false, text: "Le désert d'Arabie" },
      { challengeId: 167, correct: false, text: "Le désert de Gobi" },
      { challengeId: 168, correct: true, text: "Les Égyptiens" },
      { challengeId: 168, correct: false, text: "Les Grecs" },
      { challengeId: 168, correct: false, text: "Les Romains" },
      { challengeId: 169, correct: true, text: "Léonard de Vinci" },
      { challengeId: 169, correct: false, text: "Michel-Ange" },
      { challengeId: 169, correct: false, text: "Raphaël" },
      { challengeId: 170, correct: true, text: "1789" },
      { challengeId: 170, correct: false, text: "1776" },
      { challengeId: 170, correct: false, text: "1804" },
      { challengeId: 171, correct: true, text: "Alexander Graham Bell" },
      { challengeId: 171, correct: false, text: "Thomas Edison" },
      { challengeId: 171, correct: false, text: "Nikola Tesla" },
      { challengeId: 172, correct: true, text: "Vincent van Gogh" },
      { challengeId: 172, correct: false, text: "Pablo Picasso" },
      { challengeId: 172, correct: false, text: "Claude Monet" },
      { challengeId: 173, correct: true, text: "Victor Hugo" },
      { challengeId: 173, correct: false, text: "Émile Zola" },
      { challengeId: 173, correct: false, text: "Gustave Flaubert" },
      { challengeId: 174, correct: true, text: "H₂O" },
      { challengeId: 174, correct: false, text: "CO₂" },
      { challengeId: 174, correct: false, text: "NaCl" },
      { challengeId: 175, correct: true, text: "Mercure" },
      { challengeId: 175, correct: false, text: "Vénus" },
      { challengeId: 175, correct: false, text: "Mars" },
      { challengeId: 176, correct: true, text: "Alexander Fleming" },
      { challengeId: 176, correct: false, text: "Louis Pasteur" },
      { challengeId: 176, correct: false, text: "Marie Curie" },
      { challengeId: 177, correct: true, text: "Poséidon" },
      { challengeId: 177, correct: false, text: "Zeus" },
      { challengeId: 177, correct: false, text: "Hadès" },
      { challengeId: 178, correct: true, text: "Apollon" },
      { challengeId: 178, correct: false, text: "Hélios" },
      { challengeId: 178, correct: false, text: "Hermès" },
    ]);

    console.log("✅ Seeding finished successfully!");

  } catch (error) {
    console.error("❌ Error seeding database:", error);
    throw new Error("Failed to seed the database");
  }
};

main();